### ISSUE TITLE
Add Ag3.0 CNV information

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/vector-data#31]
Add information on how to access data from the Ag3.0 CNV resource.

**Comment by alimanfoo** [comment]
Initial content resolved via #28.

**Comment by alimanfoo** [comment]
Hi @cclarkson, @jonbrenas, I've deployed some initial content for the Ag3 CNV release, I'd be grateful if you could take a look. Three areas of new content:

* The Ag3 cloud data access page has a new [CNV section](https://malariagen.github.io/vector-data/ag3/cloud.html#copy-number-variation-cnv-data)
* The Ag3 data downloads page has a new [CNV section](https://malariagen.github.io/vector-data/ag3/download.html#copy-number-variation-cnv-data)
* There is a new [CNV analysis example notebook](https://malariagen.github.io/vector-data/ag3/examples/cnv-explore.html)

Feel free to drop any comments/suggestions as comments on this issue, and/or make a PR with any proposed changes.

**Comment by cclarkson** [comment]
Hi @alimanfoo, 

I've run the new notebook (in qhub) and checked out the two new sections (cloud access/downloads) and it all looks good to me.

:+1:

**Comment by alimanfoo** [comment]
Thanks so much Chris, closing.
