### ISSUE TITLE
Add Ag3.10 release page

### ISSUE THREAD

**Issue by leehart** [malariagen/vector-data#70]
- [x] Add `docs/ag3/ag3.10.ipynb`
- [x] Update `docs/_toc.yml`

**Comment by leehart** [comment]
Hi @ahernank 

I noticed that the Ag3.9 notebook for the VUP used the environment `developer-developer-training-nb-maintenance-mgen-8.7.0`. Should Ag3.10 use the more recent environment, i.e. version 9.0.0? What's the importance/relevance of the environment here? 

I also noticed that the VUP notebooks are still using the `data` email address rather than the `support` email address. Should they all be changed, or are we using different email addresses for different things?

**Comment by leehart** [comment]
I'm also wondering if we should change
```python
!pip install -qq malariagen_data
```
to
```python
%pip install -qq malariagen_data
```

**Comment by leehart** [comment]
I'm also wondering if we need to update all the URLs from `data` to `data_package` for all of the existing VUP notebooks, e.g.
- ag3.9.ipynb currently has https://www.malariagen.net/data/ag39-anopheles-gambiae-data-resource (which gives 404) whereas `data_package` works: https://www.malariagen.net/data_package/ag39-anopheles-gambiae-data-resource/

**Comment by leehart** [comment]
I noticed that the `study_url` returned by the data API for fontaine-2015-rebuild currently leads to a 404:
- https://www.malariagen.net/network/where-we-work/fontaine-2015-rebuild

The Ag3.10 will be using the doi.org URL instead anyway, which I got from this page:
- https://www.malariagen.net/data_package/ag310-anopheles-gambiae-data-resource/
- i.e. https://doi.org/10.1126/science.1258524

**Comment by ahernank** [comment]
Thanks @leehart! Yup - https://github.com/malariagen/vector-ops/issues/2249.
