### ISSUE TITLE
Numpy version issue with malariagen_data package

### ISSUE THREAD

**Issue by Elpastore** [malariagen/vector-data#79]
I am trying to install malariagen_data package and importing it in colab. However i am getting issue, with the current version of numpy using in colab which 2.0.2. Here is the error i am getting when installing packages:
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
accelerate 0.32.1 requires numpy<2.0.0,>=1.17, but you have numpy 2.0.2 which is incompatible.
albucore 0.0.13 requires numpy<2,>=1.24.4, but you have numpy 2.0.2 which is incompatible.
arviz 0.18.0 requires numpy<2.0,>=1.23.0, but you have numpy 2.0.2 which is incompatible.
cudf-cu12 24.4.1 requires numpy<2.0a0,>=1.23, but you have numpy 2.0.2 which is incompatible.
cudf-cu12 24.4.1 requires pandas<2.2.2dev0,>=2.0, but you have pandas 1.5.3 which is incompatible.
cupy-cuda12x 12.2.0 requires numpy<1.27,>=1.20, but you have numpy 2.0.2 which is incompatible.
gensim 4.3.3 requires numpy<2.0,>=1.18.5, but you have numpy 2.0.2 which is incompatible.
google-colab 1.0.0 requires pandas==2.1.4, but you have pandas 1.5.3 which is incompatible.
ibis-framework 8.0.0 requires numpy<2,>=1, but you have numpy 2.0.2 which is incompatible.
rmm-cu12 24.4.0 requires numpy<2.0a0,>=1.23, but you have numpy 2.0.2 which is incompatible.
scikit-learn 1.3.2 requires numpy<2.0,>=1.17.3, but you have numpy 2.0.2 which is incompatible.
tensorflow 2.17.0 requires numpy<2.0.0,>=1.23.5; python_version <= "3.11", but you have numpy 2.0.2 which is incompatible.
thinc 8.2.5 requires numpy<2.0.0,>=1.19.0; python_version >= "3.9", but you have numpy 2.0.2 which is incompatible.
transformers 4.42.4 requires numpy<2.0,>=1.17, but you have numpy 2.0.2 which is `
 So i read from the error that the depencies require version below it.
When i try to import the package it show me this error: `np.bool` was a deprecated alias for the builtin `bool` .....The aliases was originally deprecated in NumPy 1.20.
Is there any solution except usign virtual environment because this doesn't works, or are you going to change this `np.bool` notation from the source code.
Thank you for your feedback

**Comment by ahernank** [comment]
Hi @Elpastore, thanks so much for flagging this up. This issue has now been solved in the malariagen_data package, you should be able to use the package in colab without seeing these problems. Please do let us know if you are still experiencing any problems with installation..
