### ISSUE TITLE
Update env to drop defaults conda channel

### ISSUE THREAD

**Issue by ahernank** [malariagen/vector-data#92]
We need to:
- [ ] Update the `environment.yml` to not have the reference to the defaults channel
- [ ] Check the env works for the NBs (i.e. release guides)
- [ ] Re=run and update the NBs to use the new environment.

**Comment by leehart** [comment]
Closing this issue as not planned. I'll create a new issue with the new plan to:
- Remove the `environment.yml`.
- Remove the Colab link from the notebooks.
